### ISSUE TITLE
Also rotate the touchscreen input

### ISSUE THREAD

**Issue by archisman-panigrahi** [raspberrypi-ui/raindrop#1]
While raindrop rotates the screen, the touchscreen input remains the same (as a result of that, touching a part of rotated screen registers a touch event in another corner).

It would be great if raindrop also detects if a touchscreen is present and rotates the input. Other DEs like GNOME or KDE support doing this in Wayland, so this is definitely possible with some command (that I don't know of).

I once made such an application for rotating tablet screen and touch input in Raspberry Pi OS, https://github.com/archisman-panigrahi/surface-RT-screen-rotator/ (most other desktop environments have inbuilt support for doing so). It used xrandr for screen rotation and xinput for touch input rotator, but those tools don't work in wayland.

---

By the way, the quality of image in the rotated screen in wayland is way better than that in x11 (which is a bit blurry).

**Comment by spl237** [comment]
Raindrop already does this - it works on the touchscreens I have tried it on.

It is done in labwc by creating an association in the compositor between the libinput driver for the touchscreen and the display.

I suspect you have not associated the touch screen with the display - right-click the display in raindrop and choose Touchscreen from the menu that pops up - then select the driver name for the touchscreen you want to use with it.

 If you look in .config/labwc/rc.xml, you should find a line in the touch section which contains tags for deviceName and mapToOutput with your touch device and display. If that line is present and touchscreen rotation is not working, then that may be a problem with the driver for your particular screen.

**Comment by archisman-panigrahi** [comment]
Thank you for the quick reply. I am traveling. I will test and get back on this on Monday.
